name: Build flask container
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/docker_build.yml

jobs:
  build:
    name: Build image
    runs-on: [self-hosted, Linux, docker-rootless]
    env:
      IMAGE_NAME: ubi-flask
      REGISTRY: ghcr.io/major
    steps:
      - name: show the env
        run: printenv
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Hello world action step
        id: hello
        uses: two-bit-code/hello-world-docker-action@newbloke82-patch-1
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'registry.access.redhat.com/ubi8-init:8.7-6'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
